[package]
name = "monitoring-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.0.0"
monitoring = { path = "../monitoring" }
getrandom = { version = "0.2.12", features = ["js"] }
serde = "1.0.192"
serde_json = "1.0.108"
